export interface Performance{
  access_token?: string,
  user_id?: number,
  from_date?: string,
  to_date?: string,
  date_format?: string,
  employee_type?: string,
  job_know?: string,
  job_know_commrnt?: string,
  quality?: string,
  quality_comment?: string,
  punctuality?: string,
  punctuality_comment?: string,
  productivity?: string,
  productivity_comment?: string,
  communication?: string,
  communication_comment?: string,
  dependability?: string,
  dependability_comment?: string,
  additional_comment?: string,
  goal_comment?: string,
  e_name?: string,
  e_date?: string,
  s_name?: string,
  s_date?: string,
  company_id?: number,
  id?:number
}
